baseurl = "https://klaralinn.com"
languageCode = "en-us"
title = "klaralinn.com"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 5
#disqusShortname = "shortname"
#googleAnalytics = ""
pluralizeListTitles = false
# Set the followings to true as part of your site SEO
enableRobotsTXT = true
canonifyURLs = true

[params]
  description          = "what's up bitches"
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle          = "klaralinn.com"
  # Sets where "View More Posts" links
  viewMorePostLink     = "/post/"

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = false
  # Sets RSS icons to appear on the sidebar with the social media buttons
  #rssAppearAtTop       = true
  #rssAppearAtBottom    = true
  # Sets Social Media icons to appear on the sidebar
  socialAppearAtTop    = true
  #socialAppearAtBottom = true
  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # set to show or to hide categories in the sidebar
  showSidebarCategories = true
  # Sets Estimated Reading Time to appear in post headers
  includeReadingTime   = true

  # Sets the Favicon and Version for the site. Default support is for
  # apple-touch-icon-precomposed.png, favicon.png, favicon.ico, and mstile.png.
  # These are stored in the favicon folder. See the following for more information:
  # https://github.com/audreyr/favicon-cheat-sheet
  loadFavicon          = false
  faviconVersion       = ""

  # Sets Social Share links to appear on posts
  socialShare          = true
  # Sets specific share to appear on posts (default behavior is to appear)
  socialShareTwitter   = true
  socialShareGoogleplus = false
  socialShareFacebook  = true
  socialShareReddit    = false
  socialShareLinkedin  = false
  socialShareStumbleupon = false
  socialSharePinterest = true
  socialShareEmail     = true

  # Load custom CSS or JavaScript files. The variable is an array so that you
  # can load multiple files if necessary. You can also load the standard theme
  # files by adding the value, "default".
  # customCSS            = ["default", "/path/to/file"]
  # customJS             = ["default", "/path/to/file"]
  customCSS            = ["default"]
  customJS             = ["default"]
  disable_highlight = true # set to true to disable Highlight

[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
    sidebar = 5

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  identifier = "fa fa-id-card-o"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "/post/"
  identifier = "fa fa-newspaper-o"
  weight = 3

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  identifier = "fa fa-sitemap"
  weight = 5
